### ISSUE TITLE
New Logo/Icon For Tsutaeru

### ISSUE THREAD

**Issue by zularizal** [zaclimon/Tsutaeru#4]
Hi @zaclimon , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by zaclimon** [comment]
Ohh that's nice, thanks! :smile: I would like to change the design of the logo but only so it can fit into the Material Design guidelines. Do you think you can do this?

**Comment by zularizal** [comment]
Sure, please wait, i will design it

**Comment by zularizal** [comment]
HI @zaclimon , What do you think about this? If you want something changed or a new logo let me know.

![tsutaeru](https://user-images.githubusercontent.com/38547278/41197199-76b9eeba-6c7f-11e8-8417-ab0def4a095c.png)

**Comment by zaclimon** [comment]
Thanks for this proposition, I would like however to keep the colors from the current logo. Perhaps adjusting the TV so it can have a drop shadow would be neat but I'm not looking for a revamp of the actual assets.

**Comment by zularizal** [comment]
Do you want the logo to actually look like a design material and just add a material style to the new logo?

**Comment by zaclimon** [comment]
I would personally just like to adjust the current logo so it can have a material feel. As you can see the current logo looks like this:

![TsutaeruLogo](https://lh3.googleusercontent.com/1bVQuFNIZw5q3Ww2irbWXVq2OHJ77fVbieOuc0HkFe50HV1sg0_wUr2Lkxhs1Ozh1Fg3=s180-rw)

**Comment by zularizal** [comment]
Hi, sorry for late respon, how about this?

![rect4185](https://user-images.githubusercontent.com/38547278/41639390-bf2b7a64-7487-11e8-8e03-3eb30ea0d703.png)

**Comment by zaclimon** [comment]
Ohh I do like the first logo variation! Do you need the editable files (PSD's/SVG's) since it might help you into getting the best representation possible?

**Comment by zularizal** [comment]
Okay, I need the svg logo, maybe it can help

**Comment by zaclimon** [comment]
Sorry for the long reply, here's the SVG:

https://drive.google.com/open?id=1v77iLld35YpixwwtX_6DfWqU91NWTfu1

Note that you will need to remove the "Tsutaeru" text since it is bundled alongside the logo.

**Comment by zularizal** [comment]
![svgjsg1035](https://user-images.githubusercontent.com/38547278/41951423-174fb8d2-79f5-11e8-8e20-eecbe31fec44.png)


Hi, this is logo file
https://drive.google.com/open?id=1a6mTVzjFNeut_OYDp1KL8DHagP_E6nko

**Comment by zaclimon** [comment]
Ohhh that looks great! :smile:  Thanks for looking into this. I'll implement it in the app in a few days.

**Comment by zularizal** [comment]
Okay, i will close this issue
