### ISSUE TITLE
Your Credentials are Not Valid Error

### ISSUE THREAD

**Issue by pr3tty8oyfl0yd** [zaclimon/Tsutaeru#5]
I seem to be getting this error no matter what Panel URL or Service URL I try. I am not sure why that would be? Has anyone else experienced this?

**Comment by zaclimon** [comment]
I just wanted to check up on this, Is the issue still happening now?

**Comment by zaclimon** [comment]
Closing this issue since there haven't been any replies. Feel free to open another one if you have further issues.

**Comment by AlbertEinsteinGlitchPoint** [comment]
hi me too haing trouble login, i have other app working ok using same url:port  and same user and pass, but on this app it allways says invalid credentials
