### ISSUE TITLE
Xtream-Codes-API.md

### ISSUE THREAD

**Issue by aslasahari** [zaclimon/Tsutaeru#8]
hello , i need some information about this api !
Xtream-Codes-API.md 

the End point script , where can i get it ? thank you in advanced

**Comment by zaclimon** [comment]
From what I see, there is the player API that can be used.
https://forum.xtream-codes.com/topic/3511-how-to-player-api-v2/

However, Tsutaeru uses the endpoint used by Xtream Codes specific Android apps when a call is being made. You can find more info this here:

https://github.com/zaclimon/xipl/wiki/Xtream-Codes-API

Hope it helps! Closing this issue.

**Comment by aslasahari** [comment]
hello sir , can i have the source code for this script ?
http://mikkm.xyz/android/androidApi.php

i need to create m3u list with optins , and control the output for it
if you can help me with that i will be real thankfull

________________________________

**Comment by zaclimon** [comment]
I sadly don't have the source code since it is restricted and I do not work for Xtream Codes in any way. If that were the case, I would probably have found some interesting options.

**Comment by aslasahari** [comment]
ok sir can i have a copy of the file ? without the source just a copy ...

**Comment by zaclimon** [comment]
I don't have anything related to the said file. I only do requests to the API and that is the only thing possible on my end.

**Comment by aslasahari** [comment]
yes i see , thank you 
so , is there any option to select the output on this api ?

**Comment by zaclimon** [comment]
Please check the documentation on it below:

https://github.com/zaclimon/xipl/wiki/Xtream-Codes-API

There should be information about the output. I will close the conversation since I believe that the question has been answered.
